{"Asctime": "2020-03-24 11:29:34,301", "Filename": "autoreload.py", "Lineno": 217, "Levelname": "INFO", "FuncName": "trigger_reload", "Message": "/home/brijesh/5g_cps/Python/udm/framwork/testAutomationTool/apiHandler/ueAuthentication/ueAuthentication.py changed, reloading."}
{"Asctime": "2020-03-24 11:31:01,358", "Filename": "autoreload.py", "Lineno": 217, "Levelname": "INFO", "FuncName": "trigger_reload", "Message": "/home/brijesh/5g_cps/Python/udm/framwork/testAutomationTool/apiHandler/ueAuthentication/ueAuthentication.py changed, reloading."}
{"Asctime": "2020-03-24 11:34:07,132", "Filename": "autoreload.py", "Lineno": 217, "Levelname": "INFO", "FuncName": "trigger_reload", "Message": "/home/brijesh/5g_cps/Python/udm/framwork/testAutomationTool/apiHandler/ueAuthentication/ueAuthentication.py changed, reloading."}
{"Asctime": "2020-03-24 11:34:29,964", "Filename": "ueAuthentication.py", "Lineno": 149, "Levelname": "INFO", "FuncName": "post", "Message": "request args {'supportedFeatures': '3f66afa6', 'servingNetworkName': '5G:mnc480.mcc311.3gppnetwork.org', 'resynchronizationInfo': {'rand': '31323131353836343132313135383634', 'auts': '3132313135383634313231313538'}, 'ausfInstanceId': '3fa85f64-5717-4562-b3fc-2c963f66afa6'} supiOrSuci imsi-2834732467"}
{"Asctime": "2020-03-24 11:34:29,972", "Filename": "connectionpool.py", "Lineno": 225, "Levelname": "DEBUG", "FuncName": "_new_conn", "Message": "Starting new HTTP connection (1): 127.0.0.1:8005"}
{"Asctime": "2020-03-24 11:34:29,976", "Filename": "ueAuthentication.py", "Lineno": 193, "Levelname": "ERROR", "FuncName": "post", "Message": "exception Traceback (most recent call last):\n  File \"/home/brijesh/5g_cps/Python/udm/framwork/testAutomationTool/apiHandler/ueAuthentication/ueAuthentication.py\", line 159, in post\n    if res.status_code != 200:\nAttributeError: 'bool' object has no attribute 'status_code'\n"}
{"Asctime": "2020-03-24 11:34:29,977", "Filename": "log.py", "Lineno": 228, "Levelname": "ERROR", "FuncName": "log_response", "Message": "Internal Server Error: /nudm-ueau/v1/imsi-2834732467/security-information/generate-auth-data/"}
{"Asctime": "2020-03-24 11:42:03,114", "Filename": "autoreload.py", "Lineno": 217, "Levelname": "INFO", "FuncName": "trigger_reload", "Message": "/home/brijesh/5g_cps/Python/udm/framwork/testAutomationTool/apiHandler/ueAuthentication/ueAuthentication.py changed, reloading."}
{"Asctime": "2020-03-24 11:42:06,975", "Filename": "ueAuthentication.py", "Lineno": 151, "Levelname": "INFO", "FuncName": "post", "Message": "request args {'supportedFeatures': '3f66afa6', 'servingNetworkName': '5G:mnc480.mcc311.3gppnetwork.org', 'resynchronizationInfo': {'rand': '31323131353836343132313135383634', 'auts': '3132313135383634313231313538'}, 'ausfInstanceId': '3fa85f64-5717-4562-b3fc-2c963f66afa6'} supiOrSuci imsi-2834732467"}
{"Asctime": "2020-03-24 11:42:06,986", "Filename": "connectionpool.py", "Lineno": 225, "Levelname": "DEBUG", "FuncName": "_new_conn", "Message": "Starting new HTTP connection (1): 127.0.0.1:8005"}
{"Asctime": "2020-03-24 11:42:06,991", "Filename": "ueAuthentication.py", "Lineno": 195, "Levelname": "ERROR", "FuncName": "post", "Message": "exception Traceback (most recent call last):\n  File \"/home/brijesh/5g_cps/Python/udm/framwork/testAutomationTool/apiHandler/ueAuthentication/ueAuthentication.py\", line 166, in post\n    logger.info(\"auth sub %s\"%(authSub))\nUnboundLocalError: local variable 'authSub' referenced before assignment\n"}
{"Asctime": "2020-03-24 11:42:06,991", "Filename": "log.py", "Lineno": 228, "Levelname": "ERROR", "FuncName": "log_response", "Message": "Internal Server Error: /nudm-ueau/v1/imsi-2834732467/security-information/generate-auth-data/"}
{"Asctime": "2020-03-24 11:44:22,562", "Filename": "autoreload.py", "Lineno": 217, "Levelname": "INFO", "FuncName": "trigger_reload", "Message": "/home/brijesh/5g_cps/Python/udm/framwork/testAutomationTool/apiHandler/ueAuthentication/ueAuthentication.py changed, reloading."}
{"Asctime": "2020-03-24 11:44:31,376", "Filename": "ueAuthentication.py", "Lineno": 151, "Levelname": "INFO", "FuncName": "post", "Message": "request args {'supportedFeatures': '3f66afa6', 'servingNetworkName': '5G:mnc480.mcc311.3gppnetwork.org', 'resynchronizationInfo': {'rand': '31323131353836343132313135383634', 'auts': '3132313135383634313231313538'}, 'ausfInstanceId': '3fa85f64-5717-4562-b3fc-2c963f66afa6'} supiOrSuci imsi-2834732467"}
{"Asctime": "2020-03-24 11:44:31,380", "Filename": "ueAuthentication.py", "Lineno": 195, "Levelname": "ERROR", "FuncName": "post", "Message": "exception Traceback (most recent call last):\n  File \"/home/brijesh/5g_cps/Python/udm/framwork/testAutomationTool/apiHandler/ueAuthentication/ueAuthentication.py\", line 166, in post\n    logger.info(\"auth sub %s\"%(authSub))\nUnboundLocalError: local variable 'authSub' referenced before assignment\n"}
{"Asctime": "2020-03-24 11:44:31,381", "Filename": "log.py", "Lineno": 228, "Levelname": "ERROR", "FuncName": "log_response", "Message": "Internal Server Error: /nudm-ueau/v1/imsi-2834732467/security-information/generate-auth-data/"}
{"Asctime": "2020-03-24 11:47:08,043", "Filename": "autoreload.py", "Lineno": 217, "Levelname": "INFO", "FuncName": "trigger_reload", "Message": "/home/brijesh/5g_cps/Python/udm/framwork/testAutomationTool/apiHandler/ueAuthentication/ueAuthentication.py changed, reloading."}
{"Asctime": "2020-03-24 11:47:11,759", "Filename": "ueAuthentication.py", "Lineno": 151, "Levelname": "INFO", "FuncName": "post", "Message": "request args {'supportedFeatures': '3f66afa6', 'servingNetworkName': '5G:mnc480.mcc311.3gppnetwork.org', 'resynchronizationInfo': {'rand': '31323131353836343132313135383634', 'auts': '3132313135383634313231313538'}, 'ausfInstanceId': '3fa85f64-5717-4562-b3fc-2c963f66afa6'} supiOrSuci imsi-2834732467"}
{"Asctime": "2020-03-24 11:47:11,763", "Filename": "ueAuthentication.py", "Lineno": 130, "Levelname": "INFO", "FuncName": "fiveGaka", "Message": "K <framwork.testAutomationTool.apiHandler.ueAuthentication.ueAuthentication.c_ubyte_Array_16 object at 0x7ffbb148a0d0>, RAND <framwork.testAutomationTool.apiHandler.ueAuthentication.ueAuthentication.c_ubyte_Array_16 object at 0x7ffbb148a950>, SQN <framwork.testAutomationTool.apiHandler.ueAuthentication.ueAuthentication.c_ubyte_Array_6 object at 0x7ffbb148ae18>, AMF <framwork.testAutomationTool.apiHandler.ueAuthentication.ueAuthentication.c_ubyte_Array_2 object at 0x7ffbb14a9b70>"}
{"Asctime": "2020-03-24 11:47:11,764", "Filename": "ueAuthentication.py", "Lineno": 134, "Levelname": "INFO", "FuncName": "fiveGaka", "Message": "XRES [146, 231, 151, 211, 221, 14, 207, 195]"}
{"Asctime": "2020-03-24 11:47:11,764", "Filename": "ueAuthentication.py", "Lineno": 137, "Levelname": "INFO", "FuncName": "fiveGaka", "Message": "AUTN 81d2206fe8438101143ae9e3a6f183d9"}
{"Asctime": "2020-03-24 11:47:11,764", "Filename": "ueAuthentication.py", "Lineno": 138, "Levelname": "INFO", "FuncName": "fiveGaka", "Message": "Kausf ea0414a58f71bed2910dd828829497d1dd5822134bb74414eec31648a379b443"}
{"Asctime": "2020-03-24 11:48:32,037", "Filename": "autoreload.py", "Lineno": 217, "Levelname": "INFO", "FuncName": "trigger_reload", "Message": "/home/brijesh/5g_cps/Python/udm/framwork/testAutomationTool/apiHandler/ueAuthentication/ueAuthentication.py changed, reloading."}
{"Asctime": "2020-03-24 11:50:53,328", "Filename": "autoreload.py", "Lineno": 217, "Levelname": "INFO", "FuncName": "trigger_reload", "Message": "/home/brijesh/5g_cps/Python/udm/framwork/testAutomationTool/apiHandler/ueAuthentication/ueAuthentication.py changed, reloading."}
